CREATE TABLE [dbo].[JTRN_SL_DETAIL] (
    [SL_DETAIL_NO]    BIGINT           NOT NULL,
    [OPER_BUS_SEG_CD] VARCHAR (6)      NOT NULL,
    [ACCTG_MTH]       DATETIME         NOT NULL,
    [ACCT_NO]         VARCHAR (20)     NULL,
    [TRANS_VAL_AMT]   NUMERIC (13, 2)  NULL,
    [TRANS_QTY]       NUMERIC (13, 2)  NULL,
    [BTU_FACT]        NUMERIC (12, 3)  NULL,
    [GRS_AMT]         NUMERIC (13, 2)  NULL,
    [GRS_QTY]         NUMERIC (13, 2)  NULL,
    [MAJ_PROD_CD]     VARCHAR (3)      NULL,
    [PROD_CD]         VARCHAR (3)      NULL,
    [OWNR_BA_NO]      VARCHAR (10)     NULL,
    [OWNR_INT_DEC]    NUMERIC (11, 10) NULL,
    [CTR_PTY_NO]      VARCHAR (10)     NULL,
    [PROP_NO]         VARCHAR (10)     NULL,
    [DO_TYPE_CD]      VARCHAR (3)      NULL,
    [DO_MAJ_PROD_CD]  VARCHAR (3)      NULL,
    [TIER]            INT              NULL,
    [PPN_RSN_CD]      VARCHAR (10)     NULL,
    [PRDN_DT]         DATETIME         NULL,
    [ST_CD]           CHAR (2)         NULL,
    [MMBTU_OWNR_VOL]  NUMERIC (13, 2)  NULL,
    [WELL_NO]         VARCHAR (10)     NULL,
    [COMPL_NO]        CHAR (2)         NULL,
    [DISP_CD]         NCHAR (10)       NULL,
    [NET_VOL]         NUMERIC (13, 2)  NULL,
    CONSTRAINT [PK_JTRN_SL_DETAIL] PRIMARY KEY CLUSTERED ([SL_DETAIL_NO] ASC) WITH (FILLFACTOR = 90)
);

