CREATE TABLE [dbo].[ONRRAggregate] (
    [AggregateID]                     INT             IDENTITY (1, 1) NOT NULL,
    [LeaseAgreementID]                INT             NOT NULL,
    [ProductCodeID]                   INT             NOT NULL,
    [SalesTypeID]                     INT             NOT NULL,
    [ProductionMonth]                 DATE            NOT NULL,
    [TransactionCodeID]               INT             NOT NULL,
    [AdjustmentReasonCodeID]          INT             NULL,
    [SalesVolume]                     NUMERIC (13, 2) NOT NULL,
    [GasMMBTU]                        NUMERIC (13, 2) NOT NULL,
    [SalesValue]                      NUMERIC (13, 2) NOT NULL,
    [GrossRoyaltyValue]               NUMERIC (13, 2) NOT NULL,
    [TransortationAllowanceDeduction] NUMERIC (13, 2) NOT NULL,
    [ProcessingAllowanceDeduction]    NUMERIC (13, 2) NOT NULL,
    [NetRoyaltyValue]                 NUMERIC (13, 2) NOT NULL,
    [FileID]                          INT             NOT NULL,
    [PADNumber]                       VARCHAR (8)     NULL,
    [PayorCodeID]                     INT             NULL,
    [StatusID]                        INT             NOT NULL,
    [PaymentMethodID]                 INT             NULL,
    CONSTRAINT [PK_ONRRAggregate] PRIMARY KEY CLUSTERED ([AggregateID] ASC),
    CONSTRAINT [FK_ONRRAggregate_AdjustmentReasonCodes] FOREIGN KEY ([AdjustmentReasonCodeID]) REFERENCES [dbo].[AdjustmentReasonCodes] ([AdjustmentReasonCodeID]),
    CONSTRAINT [FK_ONRRAggregate_ONRRFiles] FOREIGN KEY ([FileID]) REFERENCES [dbo].[ONRRFiles] ([FileID]),
    CONSTRAINT [FK_ONRRAggregate_ONRRTransactionCodes] FOREIGN KEY ([TransactionCodeID]) REFERENCES [dbo].[ONRRTransactionCodes] ([TransactionCodeID]),
    CONSTRAINT [FK_ONRRAggregate_PaymentMethods] FOREIGN KEY ([PaymentMethodID]) REFERENCES [dbo].[PaymentMethods] ([PaymentMethodID]),
    CONSTRAINT [FK_ONRRAggregate_PayorCodes] FOREIGN KEY ([PayorCodeID]) REFERENCES [dbo].[PayorCodes] ([PayorCodeID]),
    CONSTRAINT [FK_ONRRAggregate_ProductCodeCrossReference] FOREIGN KEY ([ProductCodeID]) REFERENCES [dbo].[ProductCodeCrossReference] ([ProductCodeID]),
    CONSTRAINT [FK_ONRRAggregate_SalesTypes] FOREIGN KEY ([SalesTypeID]) REFERENCES [dbo].[SalesTypes] ([SalesTypeID])
);

