CREATE TABLE [dbo].[ONRRDetail] (
    [SL_DETAIL_NO]                             BIGINT          NOT NULL,
    [GrossAmount]                              NUMERIC (13, 2) NOT NULL,
    [OverrideGrossAmount]                      NUMERIC (13, 2) NULL,
    [GrossQuantity]                            NUMERIC (13, 2) NOT NULL,
    [OverrideGrossQuantity]                    NUMERIC (13, 2) NULL,
    [TransactionValueAmount]                   NUMERIC (13, 2) NOT NULL,
    [OverrideTransactionValueAmount]           NUMERIC (13, 2) NULL,
    [TransactionQuantity]                      NUMERIC (13, 2) NOT NULL,
    [OverrideTransactionQuantity]              NUMERIC (13, 2) NULL,
    [Price]                                    NUMERIC (6, 2)  NULL,
    [LeaseAgreementID]                         INT             NOT NULL,
    [ProductCodeID]                            INT             NOT NULL,
    [StateCode]                                CHAR (2)        NOT NULL,
    [CompanyMarketedVolume]                    NUMERIC (13, 2) NULL,
    [OverrideCompanyMarketedVolume]            NUMERIC (13, 2) NULL,
    [CompanyMarketedValue]                     NUMERIC (13, 2) NULL,
    [OverrideCompanyMarketedValue]             NUMERIC (13, 2) NULL,
    [SalesVolume]                              NUMERIC (13, 2) NULL,
    [OverrideSalesVolume]                      NUMERIC (13, 2) NULL,
    [MMBTU]                                    NUMERIC (13, 2) NULL,
    [OverrideMMBTU]                            NUMERIC (13, 2) NULL,
    [SalesValue]                               NUMERIC (13, 2) NULL,
    [OverrideSalesValue]                       NUMERIC (13, 2) NULL,
    [GrossRoyaltyValue]                        NUMERIC (13, 2) NULL,
    [OverrideGrossRoyaltyValue]                NUMERIC (13, 2) NULL,
    [TransportationAllowanceDeduction]         NUMERIC (13, 2) NULL,
    [OverrideTransportationAllowanceDeduction] NUMERIC (13, 2) NULL,
    [ProcessingAllowanceDeduction]             NUMERIC (13, 2) NULL,
    [OverrideProcessingAllowanceDeduction]     NUMERIC (13, 2) NULL,
    [NetRoyaltyValue]                          NUMERIC (13)    NULL,
    [OverrideNetRoyaltyValue]                  NUMERIC (13, 2) NULL,
    [AggregateID]                              INT             NULL,
    [ReversalAggregateID]                      INT             NULL,
    [AccountingMonth]                          DATE            NOT NULL,
    [ProductionMonth]                          DATE            NOT NULL,
    [TransactionCodeID]                        INT             NOT NULL,
    [AdjustmentReasonCodeID]                   INT             NULL,
    [ProcessingStatusID]                       INT             NOT NULL,
    [SuspendReasonID]                          INT             NULL,
    [ONRRDetailID]                             INT             IDENTITY (1, 1) NOT NULL,
    [SalesTypeID]                              INT             NOT NULL,
    [ReversalDetailID]                         INT             NULL,
    CONSTRAINT [PK_ONRRDetail_1] PRIMARY KEY CLUSTERED ([ONRRDetailID] ASC),
    CONSTRAINT [FK_ONRRDetail_AdjustmentReasonCodes] FOREIGN KEY ([AdjustmentReasonCodeID]) REFERENCES [dbo].[AdjustmentReasonCodes] ([AdjustmentReasonCodeID]),
    CONSTRAINT [FK_ONRRDetail_JTRN_SL_DETAIL] FOREIGN KEY ([SL_DETAIL_NO]) REFERENCES [dbo].[JTRN_SL_DETAIL] ([SL_DETAIL_NO]),
    CONSTRAINT [FK_ONRRDetail_LeaseAgreements] FOREIGN KEY ([LeaseAgreementID]) REFERENCES [dbo].[LeaseAgreements] ([LeaseAgreementID]),
    CONSTRAINT [FK_ONRRDetail_ONRRAggregate_AggregateID] FOREIGN KEY ([AggregateID]) REFERENCES [dbo].[ONRRAggregate] ([AggregateID]),
    CONSTRAINT [FK_ONRRDetail_ONRRAggregate_ReversalAggregateID] FOREIGN KEY ([ReversalAggregateID]) REFERENCES [dbo].[ONRRAggregate] ([AggregateID]),
    CONSTRAINT [FK_ONRRDetail_ONRRTransactionCodes] FOREIGN KEY ([TransactionCodeID]) REFERENCES [dbo].[ONRRTransactionCodes] ([TransactionCodeID]),
    CONSTRAINT [FK_ONRRDetail_ProductCodeCrossReference] FOREIGN KEY ([ProductCodeID]) REFERENCES [dbo].[ProductCodeCrossReference] ([ProductCodeID]),
    CONSTRAINT [FK_ONRRDetail_SalesTypes] FOREIGN KEY ([SalesTypeID]) REFERENCES [dbo].[SalesTypes] ([SalesTypeID]),
    CONSTRAINT [FK_ONRRDetail_States] FOREIGN KEY ([StateCode]) REFERENCES [dbo].[States] ([StateCode])
);

