
CREATE PROCEDURE [Application].[JTRN_SL_DETAILUpdate] @SL_DETAIL_NO BIGINT
    ,@OPER_BUS_SEG_CD VARCHAR(6)
    ,@ACCTG_MTH DATETIME
    ,@ACCT_NO VARCHAR(20)
    ,@TRANS_VAL_AMT NUMERIC
    ,@TRANS_QTY NUMERIC
    ,@BTU_FACT NUMERIC
    ,@GRS_AMT NUMERIC
    ,@GRS_QTY NUMERIC
    ,@MAJ_PROD_CD VARCHAR(3)
    ,@PROD_CD VARCHAR(3)
    ,@OWNR_BA_NO VARCHAR(10)
    ,@OWNR_INT_DEC NUMERIC
    ,@CTR_PTY_NO VARCHAR(10)
    ,@PROP_NO VARCHAR(10)
    ,@DO_TYPE_CD VARCHAR(3)
    ,@DO_MAJ_PROD_CD VARCHAR(3)
    ,@TIER INT
    ,@PPN_RSN_CD VARCHAR(10)
    ,@PRDN_DT DATETIME
    ,@ST_CD CHAR(2)
    ,@MMBTU_OWNR_VOL NUMERIC
    ,@WELL_NO VARCHAR(10)
    ,@COMPL_NO CHAR(2)
    ,@DISP_CD NCHAR(10)
    ,@NET_VOL NUMERIC
AS
SET NOCOUNT ON

UPDATE [dbo].[JTRN_SL_DETAIL]
SET OPER_BUS_SEG_CD = @OPER_BUS_SEG_CD
    ,ACCTG_MTH = @ACCTG_MTH
    ,ACCT_NO = @ACCT_NO
    ,TRANS_VAL_AMT = @TRANS_VAL_AMT
    ,TRANS_QTY = @TRANS_QTY
    ,BTU_FACT = @BTU_FACT
    ,GRS_AMT = @GRS_AMT
    ,GRS_QTY = @GRS_QTY
    ,MAJ_PROD_CD = @MAJ_PROD_CD
    ,PROD_CD = @PROD_CD
    ,OWNR_BA_NO = @OWNR_BA_NO
    ,OWNR_INT_DEC = @OWNR_INT_DEC
    ,CTR_PTY_NO = @CTR_PTY_NO
    ,PROP_NO = @PROP_NO
    ,DO_TYPE_CD = @DO_TYPE_CD
    ,DO_MAJ_PROD_CD = @DO_MAJ_PROD_CD
    ,TIER = @TIER
    ,PPN_RSN_CD = @PPN_RSN_CD
    ,PRDN_DT = @PRDN_DT
    ,ST_CD = @ST_CD
    ,MMBTU_OWNR_VOL = @MMBTU_OWNR_VOL
    ,WELL_NO = @WELL_NO
    ,COMPL_NO = @COMPL_NO
    ,DISP_CD = @DISP_CD
    ,NET_VOL = @NET_VOL
WHERE SL_DETAIL_NO = @SL_DETAIL_NO



